class AppConstants {
  const AppConstants._();

  static const supportEmail = 'hotro@1long.vn';

  // Generated by https://www.privacypolicyonline.com
  static const String policyUrl = 'https://www.privacypolicyonline.com/live.php?token=MMrSWhNUw0rcCLSF4v51b1WLMczRpIbK';
  static const String termsUrl = 'https://www.privacypolicyonline.com/live.php?token=d3RqatNDhEjOIJe8zHLqq5V7SjMvWrBq';

  static const String onesafeProductName = '1Safe';

  // static const String depositBank = 'TECHCOMBANK - Ngân hàng TMCP Kỹ thương Việt Nam';
  // static const String depositAccountHolderName = 'CONG TY TNHH 1LONG';
  // static const String depositAccountNumber = '19039919435016';

  // // TODO: Redo this - temporary solution
  // static BankAccount oneLongDepositAccount = BankAccount(
  //   id: '',
  //   bank: const Bank(
  //     id: '',
  //     shortName: AppConstants.depositBank,
  //     enName: AppConstants.depositBank,
  //     viName: AppConstants.depositBank,
  //     iconUrl: '',
  //   ),
  //   accountHolderName: AppConstants.depositAccountHolderName,
  //   accountNumber: AppConstants.depositAccountNumber,
  //   updatedAt: DateTime.now(),
  // );

  // static const int depositDeadlineInDays = 5;
}
