name: turboship
description: A new turboship project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: any

  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  go_router: ^12.1.1
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  primer_progress_bar: ^0.3.0
  injectable: ^2.3.2
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.2
  package_info_plus: ^5.0.1
  flutter_animate: ^4.3.0
  flutter_screenutil: ^5.9.0
  # connectivity_plus: ^5.0.2
  android_id: ^0.3.6
  flutter_cache_manager: ^3.3.1
  image_gallery_saver: ^2.0.3
  firebase_core: ^2.24.0
  freezed_annotation: ^2.4.1
  smooth_page_indicator: ^1.1.0
  currency_text_input_formatter: ^2.1.10
  flutter_inappwebview: ^5.8.0
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  styled_text: ^8.1.0
  dio: ^5.4.0
  device_info_plus: ^9.1.1
  url_launcher: ^6.2.1
  jwt_decoder: ^2.0.1
  json_annotation: ^4.8.1
  loader_overlay: ^4.0.0
  # icon_forest:
  #   path: ../../icon_forest

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # code generator
  build_runner: ^2.4.6
  injectable_generator: ^2.1.5
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  flutter_gen_runner: ^5.2.0

flutter_gen:
  output: lib/presentation/resource/gen
  line_length: 160
  integrations:
    flutter_svg: true
  assets:
    enabled: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/env/
    - assets/data/
