name: turboship
description: A new turboship project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  build_runner: ^2.4.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  go_router: ^9.0.0
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  primer_progress_bar: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true
