var go = [
  {
    _id: 'fb80c35deae8c1d25f4acbbd',
    name: 'user',
    plural: 'users',
    label: 'User',
    pluralL: 'Users',
    attributes: [
      { name: '_id', type: 'text', _id: '5f6ab0bbfb54cf51242ddb6a', validators: [], validations: [] },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'email',
        label: 'email',
        _id: '0cadf0cb95bd08874aeb398e',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        name: 'firstName',
        type: 'string',
        _id: '5aab0a1efa84976ab3afea9e',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        name: 'lastName',
        type: 'string',
        _id: '040e9eeeec2ae4eb4fd1946e',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        name: 'age',
        type: 'integer',
        _id: 'dcb9b448e5bce7c8bdea1ece',
        validators: [],
        validations: [],
        relation: { name: null, type: '' },
      },
      {
        name: 'status',
        type: 'enumerator',
        _id: '077cb5ead63ef967d1adcc2c',
        validators: [],
        validations: [],
        options: 'open,closed,pending',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        name: 'avatarUrl',
        _id: '7cb7838708b53d78de6bfdee',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'city',
        _id: 'a3aef9ecb114efde29c0aed6',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'country',
        _id: 'fdbd3ba3d4f1bbbbc7cfcfca',
        relation: { type: null, name: null },
        type: 'string',
      },
      {
        validators: [],
        validations: [],
        name: 'dob',
        _id: 'dae869bbcacb1ba1defc6ae1',
        relation: { type: null, name: null },
        type: 'date',
      },
      {
        validators: [],
        validations: [],
        name: 'status',
        _id: 'deaa69fd5793cf29f62da810',
        relation: { type: null, name: null },
        type: 'enumerator',
        options: 'pending,active,closed,deactivated,blocked',
      },
      {
        validators: [],
        validations: [],
        name: 'username',
        _id: 'c16ee76ee14ce9f8c818dca3',
        relation: { type: null, name: null },
        type: 'string',
      },
    ],
  },
  {
    _id: '59abcbce7aeedbbcd15d90b13',
    name: 'article',
    label: 'Article',
    plural: 'articles',
    pluralL: 'Articles',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'type',
        label: 'Type',
        _id: 'b2f7ba1d54e96e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'title',
        label: 'Title',
        _id: 'b2f7ba1d54e96efde143eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'caption',
        label: 'Caption',
        _id: 'b2f7ba1d54e96efde313eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'body',
        label: 'Body',
        _id: 'b2f7ba1d54e96efde213eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'link',
        label: 'Link',
        _id: 'b2f7ba1d54e96efd1e13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'urlCoverImg',
        label: 'Cover Img',
        _id: 'b2f7ba1d54e96ef8de13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'urlVideo',
        label: 'Video',
        _id: 'b2f7ba1d54e96efd7e13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'language',
        label: 'Language',
        _id: 'b2f7ba1d54e966efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numComments',
        label: '# Comments',
        _id: 'b2f7ba1d54e96ef5de13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'numVotes',
        label: '# Votes',
        _id: 'b2f7ba1d54e496efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isPublished',
        label: 'Published?',
        _id: 'b2f7ba1d54e963efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'isOriginal',
        label: 'Original?',
        _id: 'b2f7ba1d54e962efde13eb8ca',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'author',
        label: 'Author',
        _id: 'cb9e4df71b51061a101b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'user', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'comments',
        label: 'Comments',
        _id: 'cb9e4df711521061a110b22ba8c',
        placeholder: 'one-to-many',
        relation: { name: 'related', type: 'otm' },
      },
    ],
  },
  {
    _id: '59abcbce73aeedbbcd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5242e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba111d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
        label: '12',
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'urlImg',
        _id: 'b2f7ba111d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
        label: '2112',
      },
    ],
  },
  {
    _id: '59abcbce73aeedbbcd151d910b13',
    name: 'badgeItem',
    label: 'BadgeItem',
    plural: 'BadgeItems',
    pluralL: 'badgesItems',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d52422e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba111d5342e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbb3cd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e2961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba11d5142e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbbcd151d190b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e9611e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba11d542e9621e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbbcd1521d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e9621e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba11d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbbcd1511d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e9611e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba11d5242e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedb1bcd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5242e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba111d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeed2bbcd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d1542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba11d2542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7ae1edbbcd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5421e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba11d5422e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeed1bbcd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5242e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba111d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeed2bbcd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e1961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba11d5432e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7aeedbb2cd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d5412e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba113d542e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    _id: '59abcbce7ae2edbbcd151d90b13',
    name: 'badge',
    label: 'Badge',
    plural: 'Badges',
    pluralL: 'badges',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'text',
        name: '_id',
        _id: 'b2f7ba1d542e1961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'name',
        _id: 'b2f7ba11d5412e961e1fde113eb8cz',
        relation: { name: null, type: '' },
      },
    ],
  },
  {
    name: 'wizard',
    label: 'Wizards',
    plural: 'wizards',
    pluralL: 'Wizards',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'email',
        label: 'email',
        _id: '0cadf0cb95bd08874aeb398e',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'firstName',
        label: 'firstName',
        _id: 'c6a9dffe4d4574ddbad05818',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'lastName',
        label: 'lastName',
        _id: 'e79282eed6b17b7629eafc24',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'dob',
        label: 'dob',
        _id: 'd63a922e7cae4ece7deceb00',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'location',
        label: 'location',
        _id: '9f4c15fb8d0bf4c3e4b58e93',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'jobTitle',
        label: 'jobTitle',
        _id: '4a29f55871dc0528590e29ba',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'industry',
        label: 'industry',
        _id: '28ae4419cfef12dfe65a3f2d',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumerator',
        name: 'patronus',
        label: 'patronus',
        options: 'a,b,c,d,e',
        placeholder: 'a,b,c,d,e',
        _id: 'ab83a9bbdb9f99eb0fabaa1e',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'potions',
        label: 'potions',
        _id: '6e226491eb3ead4c7aba7bb1',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'charms',
        label: 'charms',
        _id: 'fcae3a6cdf4ef47ae958c9d1',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'dada',
        label: 'dada',
        _id: 'f08c706bcb3ccfb7edbb2ecd',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'sex',
        label: 'sex',
        _id: '634b82adabe6f7147de9caa5',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'avatarUrl',
        label: 'avatarUrl',
        _id: '7f93acd7ad7eef3ae3cab80f',
        placeholder: '',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumeratorMulti',
        name: 'topSpells',
        label: 'topSpells',
        options: 'jinxes, hexes, charms, curses, spells, counters, healing, transfigurations',
        placeholder: 'jinxes, hexes, charms, curses, spells, counters, healing, transfigurations',
        _id: 'ff6cbccefe22cdf2ea2f637b',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumerator',
        name: 'bookAppearances',
        label: 'bookAppearances',
        _id: 'f945cbcd3c24b1e6efce9f7c',
        placeholder: '1,2,3,4,5,6,7,8',
        options: '1,2,3,4,5,6,7,8',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumerator',
        name: 'house',
        options: 'gryffindor, slytherin, hufflepuff, ravenclaw, unknown',
        placeholder: '',
        label: 'house',
        _id: 'e7c6bfa32dd8c9ad822c0ea3',
        relation: { name: null, type: '' },
      },
    ],
    _id: '7a43da35ea0ada4403ebbf4f',
  },
  {
    name: 'foo',
    label: 'Foo',
    plural: 'foos',
    pluralL: 'Foos',
    attributes: [
      {
        validators: [],
        validations: [],
        type: 'boolean',
        name: 'fooBoolean',
        label: 'Foo Boolean',
        _id: '6dcc79ee7eb4f14dc1e0ce4b',
        placeholder: 'foo boolean placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'string',
        name: 'fooString',
        label: 'Foo String',
        _id: '3d00e44df2b3bb22da6723cb',
        placeholder: 'foo string placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'text',
        name: 'fooText',
        label: 'Foo Text',
        _id: 'bcbbfc4c1547d1627cd15fe2',
        placeholder: 'foo text placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'integer',
        name: 'fooInteger',
        label: 'Foo Integer',
        _id: '25baeb5cb6b90eb3dd68ce9d',
        placeholder: 'foo integer placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'decimal',
        name: 'fooDecimal',
        label: 'Foo Decimal',
        _id: 'b0dc5b861bf1cccdffa63ae4',
        placeholder: 'foo decimal placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'date',
        name: 'fooDate',
        label: 'Foo Date',
        _id: 'ad24804ffbd5a7932701d5f1',
        placeholder: 'foo date placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'dateTime',
        name: 'fooDateTime',
        label: 'Foo Date Time',
        _id: '10ebc11ec20a1cac1e1abdfe',
        placeholder: 'foo datetime placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'array',
        name: 'fooArray',
        label: 'Foo Array',
        _id: '2acf20585fe9beac06d823d8',
        placeholder: 'foo array placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'map',
        name: 'fooMap',
        label: 'Foo Map',
        _id: '6fbadff36a541a3730eceabc',
        placeholder: 'foo map placeholder',
        relation: { name: null, type: '' },
      },
      {
        validators: [],
        validations: [],
        type: 'enumerator',
        name: 'fooEnumerator',
        label: 'Foo Enumerator',
        _id: 'df3dab2f94babfb3eb2decef',
        placeholder: 'a,b,c,',
        relation: { name: null, type: '' },
        options: 'a,b,c',
      },
      {
        validators: [],
        validations: [],
        type: 'enumeratorMulti',
        name: 'foodEnumeratorMulti',
        label: 'Foo Enum Multi',
        _id: 'd35baeae0fdea2f0aaba41ad',
        placeholder: 'a,b,c',
        relation: { name: null, type: '' },
        options: 'a,b,c',
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'fooOTM',
        label: 'Foo OTM',
        _id: '3b91bb9236bf6ae409babfed',
        placeholder: 'one-to-many',
        relation: { name: 'related', type: 'otm' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'fooMTO',
        label: 'Foo MTO',
        _id: 'cb9e4df7b51061a10b22ba8c',
        placeholder: 'many-to-one',
        relation: { name: 'related', type: 'mto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'fooOTO',
        label: 'Foo OTO',
        _id: '9ba3dbf02fd484ec618a9e8f',
        placeholder: 'one-to-one',
        relation: { name: 'related', type: 'oto' },
      },
      {
        validators: [],
        validations: [],
        type: 'relation',
        name: 'fooMTM',
        label: 'Foo MTM',
        _id: 'ec2ef0ec3cd71cfecabfbcd4',
        placeholder: 'many-to-many',
        relation: { name: 'related', type: 'mtm' },
      },
    ],
    _id: '8c5a8f9659e0f926cf0da3ff',
  },
]
