# Dockerfile
FROM node:18-alpine3.18

WORKDIR /usr/src/app

RUN apk update && apk upgrade
RUN apk add git

COPY package.json .
COPY package-lock.json ./
RUN npm install

COPY . .
EXPOSE 3000
RUN npm run build

CMD ["node", ".output/server/index.mjs"]