[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }


[context.production]
  environment = { GENERATE_URL = "https://turboship.ltran.net/.netlify/functions/build-muxter" }