[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"

[dev]
  targetPort = 3005
  functionsPort = 8888
  publish = "./.output/public/index.html"

[build]
  publish = "dist"
  command = "npm run generate"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["shikiji/onig.wasm", "tslib"]
  included_files = [
    "./netlify/functions/esm-muxter/TurboshipCJS/**",
  ]

[build.environment]
  AUTH_TOKEN_SECRET="mySecret"
  AUTH_TOKEN_EXPIRES_IN="3650 days"
  API_URL="https://turboship-64gv3lpybq-uc.a.run.app/api"

[context.production.functions]
  external_node_modules=["shikiji/onig.wasm", "tslib"]
  included_files=["./netlify/functions/build-muxter/Turboship/Turboship.js"]

[context.branch-deploy]
  command="echo 'branch-deploy'"
  [context.branch-deploy.environment]
    API_URL="https://turboship-64gv3lpybq-uc.a.run.app/api"

[context.branch-deploy.functions]
  node_bundler="esbuild"
  external_node_modules=["shikiji/onig.wasm", "tslib"]
  included_files=["./netlify/functions/esm-muxter/Turboship/Turboship.js"]