[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  targetPort = 3005
  publish = "./.output/public/index.html"
  functionsPort = 8888

[build]
  command = "nuxt generate"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["shikiji/onig.wasm", "tslib"]
  included_files = [
    "./netlify/functions/esm-muxter/TurboshipCJS/**",
  ]

[build.environment]
  AUTH_TOKEN_SECRET="mySecret"
  AUTH_TOKEN_EXPIRES_IN="3650 days"
  API_URL="https://turboship.ltran.net/api"
  GENERATE_URL="https://turboship.ltran.net/.netlify/functions/build-muxter"

[context.production]
  command="echo 'production'"
  [context.production.environment]

[context.production.functions]
  external_node_modules=["shikiji/onig.wasm", "tslib"]
  included_files=["./netlify/functions/build-muxter/Turboship/Turboship.js"]

[context.branch-deploy]
  command="echo 'branch-deploy'"
  [context.branch-deploy.environment]
    API_URL="https://turboship.ltran.net/api"
    GENERATE_URL="https://turboship.ltran.net/.netlify/functions/esm-muxter"

[context.branch-deploy.functions]
  node_bundler="esbuild"
  external_node_modules=["shikiji/onig.wasm", "tslib"]
  included_files=["./netlify/functions/esm-muxter/Turboship/Turboship.js"]