[build]
  publish = "dist"
  command = "npm run build"

[context.production]
  environment = { API_URL = "https://turboship.ltran.net/api", MONGODB_URI = "", AUTH_TOKEN_EXPIRES_IN = "3650 days", AUTH_TOKEN_SECRET = "mysecret", API_URL = "https://turboship.ltran.net/api", GENERATE_URL = "https://turboship.ltran.net/.netlify/functions/build-muxter"}

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["shikiji/onig.wasm", "tslib"]

[dev]
  publish = "./.output/public/index.html"
  targetPort = 3005