[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"

[dev]
  targetPort = 3005
  publish = "./.output/public/index.html"

[build]
  publish = "dist"
  command = "npx nuxt build --dotenv .env.production"

[context.branch-deploy]
  command="echo 'branch-deploy'"
