export const original: Entity[] = [
  {
    _id: 'fb80c35deae8c1d25f4acbbd',
    name: 'user',
    pluralSM: 'users',
    label: 'User',
    plural: 'Users',
    showAttributes: false,
    showAttributeForm: false,
    attributes: [
      {
        name: '_id',
        type: 'string',
        _id: 'cafffcf2eb6ecdbe2242343f',
        validators: [],
      },
      {
        name: 'email',
        type: 'string',
        _id: 'd337e3e6a162deeaebbeeed6',
        validators: [],
      },
      {
        name: 'firstName',
        type: 'string',
        _id: 'aaf5edfc6f703383e3bf2bdb',
        validators: [],
      },
      {
        name: 'lastName',
        type: 'string',
        _id: '319fd13af12f5573befc2f6a',
        validators: [],
      },
      {
        name: 'age',
        type: 'number',
        _id: '4aecbfc7320cfab7138d19db',
        validators: [],
      },
      {
        name: 'status',
        type: 'enumerator',
        _id: '5e4c9e85ef8fc70e18ff9053',
        validators: [],
      },
      {
        name: 'owner',
        type: 'boolean',
        _id: 'dafc23ffc14fa06cd5df45a6',
        validators: [],
      },
      {
        name: 'role',
        type: 'enumeratorMulti',
        _id: 'ca0f7cc1af22d6b5795bc8de',
        validators: [],
      },
      {
        validators: [],
        name: 'account',
        type: 'otm',
        _id: '52cd0a63e250609f3a18a14b',
      },
      {
        validators: [],
        name: 'transaction',
        type: 'otm',
        _id: '8a8c14ff01a7bcc6ebbb0a27',
      },
      {
        validators: [],
        name: 'bank',
        type: 'otm',
        _id: 'e7abb9d44614a0ab62abfdea',
      },
      {
        validators: [],
        name: 'netWorth',
        type: 'decimal',
        _id: 'dfdfc7beeba4014db382a2dc',
      },
    ],
    relationships: [
      {
        type: 'otm',
        aEntity: 'user',
        aField: 'transactions',
        bEntity: 'transaction',
        bField: 'user',
      },
    ],
    editing: false,
  },
  {
    _id: '9bb6eaefd16bcaadbadb6064',
    name: 'account',
    pluralSM: 'accounts',
    label: 'Account',
    plural: 'Accounts',
    showAttributes: false,
    showAttributeForm: false,
    attributes: [
      {
        name: '_id',
        type: 'string',
        _id: 'ae1c66c6a924cd3eb7e2c93a',
        validators: [],
      },
      {
        validators: [],
        name: 'balance',
        type: 'decimal',
        _id: '5f91bf1cf6fefa7b8d80dc8d',
      },
      {
        validators: [],
        name: 'user',
        type: 'mto',
        _id: 'f4cdb6e3e8aa5fcebaea0dda',
      },
      {
        validators: [],
        name: 'bank',
        type: 'mto',
        _id: '5b0da4e48bf37c0db9ddbd54',
      },
      {
        validators: [],
        name: 'transaction',
        type: 'otm',
        _id: 'fd0ddc0069cc7bccf25cd04b',
      },
      {
        validators: [],
        name: 'status',
        type: 'enumerator',
        _id: 'ef0e7c2a16bffbeafa97c499',
      },
      {
        validators: [],
        name: 'type',
        type: 'enumerator',
        _id: 'b1ce62c7e8fabd0f76fdddae',
      },
      {
        validators: [],
        name: 'number',
        type: 'string',
        _id: 'ce2d9dd8a6d6cbceceaf5dce',
      },
      {
        validators: [],
        name: 'routingNumber',
        type: 'string',
        _id: '3df8f2fff52ce0b53d826b78',
      },
      {
        validators: [],
        name: 'branch',
        type: 'mto',
        _id: 'ebeb744db95fdedef1d4cbb2',
      },
    ],
    relationships: [
      {
        type: 'mto',
        aEntity: 'account',
        aField: 'user',
        bEntity: 'user',
        bField: 'accounts',
      },
      {
        type: 'oto',
        aEntity: 'account',
        aField: 'bank',
        bEntity: 'bank',
        bField: 'accounts',
      },
    ],
    editing: false,
  },
  {
    _id: 'dc01d49b61bcb3208597d9e1',
    name: 'transaction',
    pluralSM: 'transactions',
    label: 'Transaction',
    plural: 'Transactions',
    showAttributes: false,
    showAttributeForm: false,
    attributes: [
      {
        name: '_id',
        type: 'string',
        _id: 'dedfcf349503b0dae749bfad',
        validators: [],
      },
      {
        validators: [],
        name: 'amount',
        type: 'decimal',
        _id: '129b10719c7c1f31ce0c8dcf',
      },
      {
        validators: [],
        name: 'status',
        type: 'enumerator',
        _id: 'c7e2b20f0ae13f76bbfd8f9e',
      },
      {
        validators: [],
        name: 'chargeDate',
        type: 'dateTime',
        _id: '0089dac780eec33adbef4283',
      },
      {
        validators: [],
        name: 'description',
        type: 'string',
        _id: 'dde07cdf5e1bf5e9f4de5772',
      },
      {
        validators: [],
        name: 'user',
        type: 'mto',
        _id: 'ce1b3abadc196ddde3491cd1',
      },
      {
        validators: [],
        name: 'account',
        type: 'mto',
        _id: '308a6232a85bc0c3f33e0ecd',
      },
      {
        validators: [],
        name: 'branch',
        type: 'mto',
        _id: 'e3ecd5e5cd2cb709cc9b8fe0',
      },
      {
        validators: [],
        name: 'bank',
        type: 'mto',
        _id: '2f9fcfb9dacb86b6c14ff072',
      },
    ],
    relationships: [
      {
        type: 'mto',
        aEntity: 'transaction',
        aField: 'user',
        bEntity: 'user',
        bField: 'transactions',
      },
      {
        type: 'mto',
        aEntity: 'transaction',
        aField: 'account',
        bEntity: 'account',
        bField: 'transactions',
      },
      {
        type: 'mto',
        aEntity: 'transaction',
        aField: 'bank',
        bEntity: 'bank',
        bField: 'transactions',
      },
    ],
    editing: false,
  },
  {
    _id: 'b4ba1f8610fd6c5badf0dd1e',
    name: 'bank',
    pluralSM: 'banks',
    label: 'Bank',
    plural: 'Banks',
    showAttributes: false,
    showAttributeForm: false,
    attributes: [
      {
        name: '_id',
        type: 'string',
        _id: 'fb503a10feba6edfc1f288f6',
        validators: [],
      },
      {
        name: 'name',
        type: 'string',
        _id: 'c0ecc1a3baf4b8408f6d1edc',
        validators: [],
      },
      {
        name: 'ceo',
        type: 'string',
        _id: '2fae3d2ffc902ed30c2ac050',
        validators: [],
      },
      {
        name: 'logoURL',
        type: 'string',
        _id: '7bbd219feab6dd01ddde26bd',
        validators: [],
      },
      {
        name: 'creditRating',
        type: 'enumerator',
        _id: 'ab6e269cc81f9438619e8d7e',
        validators: [],
      },
      {
        name: 'employeeCount',
        type: 'integer',
        _id: 'b43688dca3696de7dd7f19b7',
        validators: [],
      },
      {
        name: 'hq',
        type: 'string',
        _id: 'bc70bd153d03acfa048d2a51',
        validators: [],
      },
      {
        validators: [],
        name: 'branch',
        type: 'otm',
        _id: 'c8fefe85c7bdb9a4df8dcea4',
      },
      {
        validators: [],
        name: 'account',
        type: 'otm',
        _id: '8db7b5cec999a4ebbe9eb31f',
      },
      {
        validators: [],
        name: 'user',
        type: 'otm',
        _id: 'dc3e7b3dae6cab8d1c2fdcef',
      },
      {
        validators: [],
        name: 'transaction',
        type: 'otm',
        _id: 'cef5dcd5ef6a1a4a3daddf41',
      },
    ],
    relationships: [
      {
        type: 'one-to-many',
        aEntity: 'bank',
        aField: 'branches',
        bEntity: 'branch',
        bField: 'bank',
      },
    ],
    editing: false,
  },
  {
    _id: '32b344ad5e0cfb2645b02f3b',
    name: 'branch',
    pluralSM: 'branches',
    label: 'Branch',
    plural: 'Branches',
    showAttributes: false,
    showAttributeForm: false,
    attributes: [
      {
        name: '_id',
        type: 'string',
        _id: 'b2bddef2edbf7da4af1eefeb',
        validators: [],
      },
      {
        name: 'location',
        type: 'string',
        _id: '6fc4fd0f1c3baddeb1dfc1de',
        validators: [],
      },
      {
        name: 'phone',
        type: 'string',
        _id: 'ed0311775eeb11e0f55677db',
        validators: [],
      },
      {
        name: 'manager',
        type: 'string',
        _id: '49720a0243b58fbf0a43eaef',
        validators: [],
      },
      {
        validators: [],
        name: 'account',
        type: 'otm',
        _id: 'bed5b2db0bb476b9b66adbee',
      },
      {
        validators: [],
        name: 'user',
        type: 'otm',
        _id: '8b0cdbd65f50bcaee5f4daf5',
      },
      {
        validators: [],
        name: 'transaction',
        type: 'otm',
        _id: '4117cd04d5afe53395a5ec71',
      },
      {
        validators: [],
        name: 'bank',
        type: 'mto',
        _id: '1d5ecf5cfec0d1dc29aacdcb',
      },
    ],
    relationships: [
      {
        type: 'mto',
        aEntity: 'branch',
        aField: 'bank',
        bEntity: 'bank',
        bField: 'branches',
      },
      {
        type: 'otm',
        aEntity: 'branch',
        aField: 'users',
        bEntity: 'user',
        bField: 'branch',
      },
    ],
    editing: false,
  },
]
