<template>
  <div class="flex gap-4 hover:cursor-pointer">
    <img
      alt="fb"
      width="30"
      height="30"
      src="https://www.svgrepo.com/show/303114/facebook-3-logo.svg"
    />
    <img
      alt="tw"
      width="30"
      height="30"
      src="https://www.svgrepo.com/show/303115/twitter-3-logo.svg"
    />
    <img
      alt="inst"
      width="30"
      height="30"
      src="https://www.svgrepo.com/show/303145/instagram-2-1-logo.svg"
    />
    <a href="https://github.com/PrimeTimeTran/nuxtoverflow">
      <img
        alt="gt"
        class=""
        width="30"
        height="30"
        src="https://www.svgrepo.com/show/94698/github.svg"
      />
    </a>
    <img
      alt="pn"
      width="30"
      height="30"
      src="https://www.svgrepo.com/show/22037/path.svg"
    />
    <img
      alt="in"
      width="30"
      height="30"
      src="https://www.svgrepo.com/show/28145/linkedin.svg"
    />
    <img
      alt="db"
      width="30"
      height="30"
      src="https://www.svgrepo.com/show/22048/dribbble.svg"
    />
  </div>
</template>

<script>
import { faYammer } from '@fortawesome/free-brands-svg-icons'
</script>
