export const entitiesMeta = {
  wizards: {
    _id: { type: 'ObjectId' },
    dob: { label: 'D.O.B.', type: 'date' },
    firstName: { label: 'First Name', type: 'string' },
    lastName: { label: 'Last Name', type: 'string' },
    email: { label: 'Email', type: 'string' },
    gender: { label: 'Gender', type: 'string' },
    city: { label: 'City', type: 'string' },
    country: { label: 'Country', type: 'string' },
    jobTitle: { label: 'Job Title', type: 'string' },
    industry: { label: 'Industry', type: 'string' },
    patronus: { label: 'Patronus', type: 'string' },
    avatarUrl: { label: 'AvatarUrl', type: 'string' },
    fanScore: { label: 'Fan Score', type: 'decimal' },
    potions: { label: 'Potions', type: 'integer' },
    charms: { label: 'Charms', type: 'integer' },
    dada: { label: 'D.A.D.A.', type: 'integer' },
    apparition: { label: 'Apparition', type: 'boolean' },
    bookAppearances: { label: 'Appearances', type: 'enumeratorMulti', options: [1, 2, 3, 4, 5, 6, 7, 8] },
    house: {
      label: 'House',
      type: 'enumerator',
      options: ['gryffindor', 'slytherin', 'hufflepuff', 'ravenclaw', 'unknown'],
    },
    topSpells: {
      label: 'Top Spells',
      type: 'enumeratorMulti',
      options: ['jinxes', 'hexes', 'charms', 'curses', 'spells', 'counters', 'healing', 'transfigurations'],
    },
    languages: {
      label: 'Languages',
      type: 'enumeratorMulti',
      options: [
        'Rust',
        'C++',
        'Dart',
        'Perl',
        'COBOL',
        'Go',
        'Javascript',
        'Java',
        'Typescript',
        'Scala',
        'Ruby',
        'Swift',
        'Python',
        'Kotlin',
        'C',
        'R',
        'C#',
        'PHP',
      ],
    },
  },
}
