class AppConstants {
  static const supportEmail = '';
  // Generated by https://www.privacypolicyonline.com
  static const String policyUrl = '';
  static const String termsUrl = '';
  const AppConstants._();
}
