export const wizardSeeds = [
  {
    firstName: 'Albus',
    lastName: 'Dumbledore',
    house: 'Gryffindor',
    patronus: 'Phoenix',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Tom',
    lastName: 'Riddle',
    house: 'Slytherin',
    patronus: 'None',
    gender: 'm',
    bookAppearances: [2, 6],
  },
  {
    firstName: 'Gellert',
    lastName: 'Grindelwald',
    house: 'Unknown',
    patronus: 'None',
    gender: 'm',
  },
  {
    firstName: 'Severus',
    lastName: 'Snape',
    house: 'Slytherin',
    patronus: 'Doe',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Alastor',
    lastName: 'Moody',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Minerva',
    lastName: 'McGonagall',
    house: 'Gryffindor',
    patronus: 'Cat',
    gender: 'f',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Lily',
    lastName: 'Potter',
    house: 'Gryffindor',
    patronus: 'Doe',
    gender: 'f',
  },
  {
    firstName: 'Bellatrix',
    lastName: 'Lestrange',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Kingsley',
    lastName: 'Shacklebolt',
    house: 'Unknown',
    patronus: 'Lynx',
    gender: 'm',
  },
  {
    firstName: 'Filius',
    lastName: 'Flitwick',
    house: 'Ravenclaw',
    patronus: 'Jack Russell Terrier',
    gender: 'm',
  },
  {
    firstName: 'Barty',
    lastName: 'Crouch Jr',
    house: 'Unknown',
    patronus: 'None',
    gender: 'm',
  },
  {
    firstName: 'Amelia',
    lastName: 'Bones',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Antonin',
    lastName: 'Dolohov',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Rufus',
    lastName: 'Scrimgeour',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Horace',
    lastName: 'Slughorn',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Igor',
    lastName: 'Karkaroff',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Remus',
    lastName: 'Lupin',
    house: 'Gryffindor',
    patronus: 'Wolf',
    gender: 'm',
  },
  {
    firstName: 'Sirius',
    lastName: 'Black',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
    bookAppearances: [3],
  },
  {
    firstName: 'James',
    lastName: 'Potter',
    house: 'Gryffindor',
    patronus: 'Stag',
    gender: 'm',
  },
  {
    firstName: 'Regulus',
    lastName: 'Black',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Thorfinn',
    lastName: 'Rowle',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Nymphadora',
    lastName: 'Tonks',
    house: 'Hufflepuff',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Phineas Nigellus',
    lastName: 'Black',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Barty',
    lastName: 'Crouch Sr',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Lucius',
    lastName: 'Malfoy',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Narcissa',
    lastName: 'Malfoy',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Molly',
    lastName: 'Weasley',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Hermione',
    lastName: 'Granger',
    house: 'Gryffindor',
    patronus: 'Otter',
    gender: 'f',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Harry',
    lastName: 'Potter',
    house: 'Gryffindor',
    patronus: 'Stag',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Peter',
    lastName: 'Pettigrew',
    house: 'Gryffindor',
    patronus: 'Rat',
    gender: 'm',
  },
  {
    firstName: 'Aberforth',
    lastName: 'Dumbledore',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Corban',
    lastName: 'Yaxley',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Garrick',
    lastName: 'Ollivander',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Pomona',
    lastName: 'Sprout',
    house: 'Hufflepuff',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Arthur',
    lastName: 'Weasley',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Madame',
    lastName: 'Maxime',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Avery',
    lastName: 'Sr',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Rodolphus',
    lastName: 'Lestrange',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Augustus',
    lastName: 'Rookwood',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Cornelius',
    lastName: 'Fudge',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Dolores',
    lastName: 'Umbridge',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Pius',
    lastName: 'Thicknesse',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Madam',
    lastName: 'Pomfrey',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Bill',
    lastName: 'Weasley',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Fleur',
    lastName: 'Delacour',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Viktor',
    lastName: 'Krum',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Charlie',
    lastName: 'Weasley',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Draco',
    lastName: 'Malfoy',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Ron',
    lastName: 'Weasley',
    house: 'Gryffindor',
    patronus: 'Jack Russell Terrier',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Fenrir',
    lastName: 'Greyback',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Percy',
    lastName: 'Weasley',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Neville',
    lastName: 'Longbottom',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Gregorovitch',
    lastName: 'Unknown',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Xenophilius',
    lastName: 'Lovegood',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Sybill',
    lastName: 'Trelawney',
    house: 'Ravenclaw',
    patronus: 'None',
    gender: 'f',
  },
  {
    firstName: 'Quirinus',
    lastName: 'Quirrel',
    house: 'Unknown',
    patronus: 'None',
    gender: 'm',
    bookAppearances: [1],
  },
  {
    firstName: 'Newton',
    lastName: 'Scamander',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Elphias',
    lastName: 'Doge',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Thaddeus',
    lastName: 'Travers',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Crabbe',
    lastName: 'Sr',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Goyle',
    lastName: 'Sr',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Ginny',
    lastName: 'Weasley',
    house: 'Gryffindor',
    patronus: 'Horse',
    gender: 'f',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Luna',
    lastName: 'Lovegood',
    house: 'Ravenclaw',
    patronus: 'Hare',
    gender: 'f',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Rolanda',
    lastName: 'Hooch',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Wilhelmina',
    lastName: 'Grubbly-Plank',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Oliver',
    lastName: 'Wood',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Rabastan',
    lastName: 'Lestrange',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Antioch',
    lastName: 'Scabior',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Andromeda',
    lastName: 'Tonks',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Ludovic',
    lastName: 'Bagman',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Stanley',
    lastName: 'Shunpike',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Dirk',
    lastName: 'Gibbon',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Mafalda',
    lastName: 'Hopkirk',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Rubeus',
    lastName: 'Hagrid',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Cho',
    lastName: 'Chang',
    house: 'Ravenclaw',
    patronus: 'Unknown',
    gender: 'f',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Dean',
    lastName: 'Thomas',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Blaise',
    lastName: 'Zabini',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Seamus',
    lastName: 'Finnigan',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Ernie',
    lastName: 'Macmillan',
    house: 'Hufflepuff',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Alicia',
    lastName: 'Spinnet',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Angelina',
    lastName: 'Johnson',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'f',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Romilda',
    lastName: 'Vane',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Lee',
    lastName: 'Jordan',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Katie',
    lastName: 'Bell',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Pansy',
    lastName: 'Parkinson',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Hannah',
    lastName: 'Abbot',
    house: 'Hufflepuff',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Parvati',
    lastName: 'Patil',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'f',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Padma',
    lastName: 'Patil',
    house: 'Ravenclaw',
    patronus: 'Unknown',
    gender: 'f',
    bookAppearances: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    firstName: 'Susan',
    lastName: 'Bones',
    house: 'Hufflepuff',
    patronus: 'Unknown',
    gender: 'f',
  },
  {
    firstName: 'Cormac',
    lastName: 'McLaggen',
    house: 'Gryffindor',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Colin',
    lastName: 'Creevey',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Vincent',
    lastName: 'Crabbe',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Gregory',
    lastName: 'Goyle',
    house: 'Slytherin',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Myrtle',
    lastName: 'Warren',
    house: 'Ravenclaw',
    patronus: 'Unknown',
    gender: 'f',
    bookAppearances: [2],
  },
  {
    firstName: 'Argus',
    lastName: 'Filch',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'm',
  },
  {
    firstName: 'Arabella',
    lastName: 'Figg',
    house: 'Unknown',
    patronus: 'Unknown',
    gender: 'f',
  },
]