export const CRM = {
  server: 'nuxt',
  mobile: 'flutter',
  fbDev: {},
  fbProd: {},
  entities: [
    {
      _id: 'fb80c35deae8c1d25f4acbbd',
      name: 'user',
      plural: 'users',
      label: 'User',
      pluralL: 'Users',
      attributes: [
        {
          name: 'status',
          type: 'enumerator',
          _id: '077cb5ead63ef967d1adcc2c',
          validators: [],
          validations: [],
          options: 'pending,open,closed',
          relation: { type: null, name: null },
          label: 'Status',
          placeholder: 'pending,open,closed',
        },
        {
          name: 'standing',
          type: 'enumerator',
          _id: '077cb5ead63ef967d1adcc2d',
          validators: [],
          validations: [],
          options: 'current,behind',
          relation: { type: null, name: null },
          label: 'Standing',
          placeholder: 'current,behind',
        },
        {
          name: 'email',
          type: 'string',
          _id: '0ca1c138ce4ddacdcbbc49d6',
          validators: ['email', 'unique'],
          validations: [],
          relation: { type: null, name: null },
          label: 'Email',
          placeholder: 'john@email.com',
        },
        {
          name: 'phone',
          type: 'string',
          _id: '0ca1c138ce4ddacdcbbc49d1',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Phone',
          placeholder: '88-888-8888',
        },
        {
          name: 'firstName',
          type: 'string',
          _id: '5aab0a1efa84976ab3afea9e',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'First Name',
          placeholder: 'John',
        },
        {
          name: 'lastName',
          type: 'string',
          _id: '040e9eeeec2ae4eb4fd2946e',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Last Name',
          placeholder: 'Doe ',
        },
        {
          name: 'phone',
          type: 'string',
          _id: '040e9eeeec2ae4eb4fd1946e',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Phone',
          placeholder: '777-777-7777',
        },
        {
          name: 'role',
          type: 'enumeratorMulti',
          _id: '7f3711fe5bcb2efde166c758',
          validators: [],
          validations: [],
          options: 'owner,admin,staff,customer',
          relation: { type: null, name: null },
          label: 'Role',
          placeholder: 'customer, employee, admin',
        },
        { name: '_id', type: 'string', _id: '5f6ab0bbfb54cf51242ddb6a', validators: [], validations: [], label: '_id' },
      ],
    },
    {
      name: 'wizard',
      label: 'Wizards',
      plural: 'wizards',
      pluralL: 'Wizards',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'email',
          label: 'email',
          _id: '0cadf0cb95bd08874aeb398e',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'firstName',
          label: 'firstName',
          _id: 'c6a9dffe4d4574ddbad05818',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'lastName',
          label: 'lastName',
          _id: 'e79282eed6b17b7629eafc24',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'dob',
          label: 'dob',
          _id: 'd63a922e7cae4ece7deceb00',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'map',
          name: 'location',
          label: 'location',
          _id: '9f4c15fb8d0bf4c3e4b58e93',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'jobTitle',
          label: 'jobTitle',
          _id: '4a29f55871dc0528590e29ba',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'industry',
          label: 'industry',
          _id: '28ae4419cfef12dfe65a3f2d',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'patronus',
          label: 'patronus',
          options: 'a,b,c,d,e',
          placeholder: 'a,b,c,d,e',
          _id: 'ab83a9bbdb9f99eb0fabaa1e',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'potions',
          label: 'potions',
          _id: '6e226491eb3ead4c7aba7bb1',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'charms',
          label: 'charms',
          _id: 'fcae3a6cdf4ef47ae958c9d1',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'dada',
          label: 'dada',
          _id: 'f08c706bcb3ccfb7edbb2ecd',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'sex',
          label: 'sex',
          _id: '634b82adabe6f7147de9caa5',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'avatarUrl',
          label: 'avatarUrl',
          _id: '7f93acd7ad7eef3ae3cab80f',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumeratorMulti',
          name: 'topSpells',
          label: 'topSpells',
          options: 'jinxes, hexes, charms, curses, spells, counters, healing, transfigurations',
          placeholder: 'jinxes, hexes, charms, curses, spells, counters, healing, transfigurations',
          _id: 'ff6cbccefe22cdf2ea2f637b',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'bookAppearances',
          label: 'bookAppearances',
          _id: 'f945cbcd3c24b1e6efce9f7c',
          placeholder: '1,2,3,4,5,6,7,8',
          options: '1,2,3,4,5,6,7,8',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'house',
          options: 'gryffindor, slytherin, hufflepuff, ravenclaw, unknown',
          placeholder: '',
          label: 'house',
          _id: 'e7c6bfa32dd8c9ad822c0ea3',
          relation: { name: null, type: '' },
        },
      ],
      _id: '7a43da35ea0ada4403ebbf4f',
    },
    {
      name: 'foo',
      label: 'Foo',
      plural: 'foos',
      pluralL: 'Foos',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'fooBoolean',
          label: 'Foo Boolean',
          _id: '6dcc79ee7eb4f14dc1e0ce4b',
          placeholder: 'foo boolean placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'fooString',
          label: 'Foo String',
          _id: '3d00e44df2b3bb22da6723cb',
          placeholder: 'foo string placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'fooText',
          label: 'Foo Text',
          _id: 'bcbbfc4c1547d1627cd15fe2',
          placeholder: 'foo text placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'fooInteger',
          label: 'Foo Integer',
          _id: '25baeb5cb6b90eb3dd68ce9d',
          placeholder: 'foo integer placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'fooDecimal',
          label: 'Foo Decimal',
          _id: 'b0dc5b861bf1cccdffa63ae4',
          placeholder: 'foo decimal placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'date',
          name: 'fooDate',
          label: 'Foo Date',
          _id: 'ad24804ffbd5a7932701d5f1',
          placeholder: 'foo date placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'fooDateTime',
          label: 'Foo Date Time',
          _id: '10ebc11ec20a1cac1e1abdfe',
          placeholder: 'foo datetime placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'fooArray',
          label: 'Foo Array',
          _id: '2acf20585fe9beac06d823d8',
          placeholder: 'foo array placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'map',
          name: 'fooMap',
          label: 'Foo Map',
          _id: '6fbadff36a541a3730eceabc',
          placeholder: 'foo map placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'fooEnumerator',
          label: 'Foo Enumerator',
          _id: 'df3dab2f94babfb3eb2decef',
          placeholder: 'singleA,singleB,singleC,singleD,singleE,singleF,singleG',
          relation: { name: null, type: '' },
          options: 'singleA,singleB,singleC,singleD,singleE,singleF,singleG',
        },
        {
          validators: [],
          validations: [],
          type: 'enumeratorMulti',
          name: 'foodEnumeratorMulti',
          label: 'Foo Enum Multi',
          _id: 'd35baeae0fdea2f0aaba41ad',
          placeholder: 'multiA,multiB,multiC,multiD,multiE,multiF,multiG',
          relation: { name: null, type: '' },
          options: 'multiA,multiB,multiC,multiD,multiE,multiF,multiG',
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'fooOTM',
          label: 'Foo OTM',
          _id: '3b91bb9236bf6ae409babfed',
          placeholder: 'one-to-many',
          relation: { name: 'user', type: 'otm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'fooMTO',
          label: 'Foo MTO',
          _id: 'cb9e4df7b51061a10b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'fooOTO',
          label: 'Foo OTO',
          _id: '9ba3dbf02fd484ec618a9e8f',
          placeholder: 'one-to-one',
          relation: { name: 'user', type: 'oto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'fooMTM',
          label: 'Foo MTM',
          _id: 'ec2ef0ec3cd71cfecabfbcd4',
          placeholder: 'many-to-many',
          relation: { name: 'user', type: 'mtm' },
        },
      ],
      _id: '8c5a8f9659e0f926cf0da3ff',
    },
    {
      name: 'rating',
      label: 'Rating',
      plural: 'ratings',
      pluralL: 'Ratings',
      attributes: [
        {
          type: 'relation',
          relation: { type: 'mto', name: 'user' },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'user',
          label: 'User',
          _id: 'f18ef63e20fba6d2cf1aadee',
        },
        {
          type: 'decimal',
          relation: { type: '', name: null },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'score',
          label: 'Score',
          _id: '7c7a329cf3ecf2b40ebce583',
        },
        {
          type: 'relation',
          relation: { type: 'oto', name: 'review' },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'review',
          label: 'Review',
          _id: 'aed3e4e7cc00ccdd3d8c8fba',
        },
      ],
      _id: 'cd2ccfefec8da26216abf999',
    },
    {
      name: 'review',
      label: 'Review',
      plural: 'reviews',
      pluralL: 'Reviews',
      attributes: [
        {
          type: 'relation',
          relation: { type: 'mto', name: 'user' },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'user',
          label: 'User',
          _id: 'be8abe69cf07f9b40dbd2b58',
        },
        {
          type: 'string',
          relation: { type: '', name: null },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'title',
          label: 'Title',
          _id: '1c8bd9b2ef6d9ecdbd804dd0',
        },
        {
          type: 'text',
          relation: { type: '', name: null },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'body',
          label: 'Body',
          _id: 'dc34b2d680fccf1eecc6f8d1',
        },
        {
          type: 'boolean',
          relation: { type: '', name: null },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'resolved',
          label: 'Resolved',
          _id: 'eacd14effe3c67daa9b5e6ae',
        },
        {
          validators: [],
          validations: [],
          name: 'rating',
          label: 'Rating',
          _id: 'cfc0d1a8e175708ea0d8388e',
          relation: { type: 'oto', name: 'rating' },
          type: 'relation',
        },
      ],
      _id: 'aa76974a5558fa4d5fffda81',
    },
    {
      name: 'chat',
      label: 'Chat',
      plural: 'chats',
      pluralL: 'Chats',
      attributes: [
        {
          type: 'string',
          relation: { type: '', name: null },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'name',
          label: 'Name',
          _id: 'debdccf8313071ec8d530e4b',
        },
        {
          type: 'relation',
          relation: { type: 'otm', name: 'message' },
          validators: [],
          validations: [],
          placeholder: '',
          options: [],
          name: 'messages',
          label: 'Messages',
          _id: 'e4f4bf3e26f6cf5bdcaad5f3',
        },
        {
          type: 'relation',
          relation: { type: 'otm', name: 'user' },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'users',
          label: 'Users',
          _id: 'c9f2d29ddb542fcf4faebfd6',
        },
      ],
      _id: 'c33e88dadf0529d531a82072',
    },
    {
      name: 'message',
      label: 'Message',
      plural: 'messages',
      pluralL: 'Messages',
      attributes: [
        {
          type: 'relation',
          relation: { type: 'mto', name: 'user' },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'user',
          label: 'User',
          _id: '29f4703de5dd585f84391f4c',
        },
        {
          type: 'text',
          relation: { type: '', name: null },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'body',
          label: 'Body',
          _id: 'fd21b9e64b478f1b9dfaf982',
        },
        {
          type: 'relation',
          relation: { type: 'mto', name: 'chat' },
          validators: [],
          validations: [],
          placeholder: '',
          options: '',
          name: 'chat',
          label: 'Chat',
          _id: 'cffcf42e05849ec8cc03ab7e',
        },
        {
          type: 'enumerator',
          relation: { type: '', name: null },
          validators: [],
          validations: [],
          placeholder: '',
          options: 'internal,customer',
          name: 'type',
          label: 'Type',
          _id: '81af5aa0ce0640aa07d8aa52',
        },
      ],
      _id: '4badea8ada53befd2efef75c',
    },
  ],
}
