export const Exchange = {
  server: 'nuxt',
  mobile: 'flutter',
  fbDev: {},
  fbProd: {},
  entities: [
    {
      _id: 'fb80c35deae8c1d25f4acbbd',
      name: 'user',
      plural: 'users',
      label: 'User',
      pluralL: 'Users',
      attributes: [
        {
          name: 'status',
          type: 'enumerator',
          _id: '077cb5ead63ef967d1adcc2c',
          validators: [],
          validations: [],
          options: 'pending,open,closed',
          relation: { type: null, name: null },
          label: 'Status',
          placeholder: 'pending,open,closed',
        },
        {
          name: 'standing',
          type: 'enumerator',
          _id: '077cb5ead63ef967d1adcc2d',
          validators: [],
          validations: [],
          options: 'current,behind',
          relation: { type: null, name: null },
          label: 'Standing',
          placeholder: 'current,behind',
        },
        {
          name: 'email',
          type: 'string',
          _id: '0ca1c138ce4ddacdcbbc49d6',
          validators: ['email', 'unique'],
          validations: [],
          relation: { type: null, name: null },
          label: 'Email',
          placeholder: 'john@email.com',
        },
        {
          name: 'phone',
          type: 'string',
          _id: '0ca1c138ce4ddacdcbbc49d1',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Phone',
          placeholder: '88-888-8888',
        },
        {
          name: 'firstName',
          type: 'string',
          _id: '5aab0a1efa84976ab3afea9e',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'First Name',
          placeholder: 'John',
        },
        {
          name: 'lastName',
          type: 'string',
          _id: '040e9eeeec2ae4eb4fd2946e',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Last Name',
          placeholder: 'Doe ',
        },
        {
          name: 'phone',
          type: 'string',
          _id: '040e9eeeec2ae4eb4fd1946e',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Phone',
          placeholder: '777-777-7777',
        },
        {
          name: 'role',
          type: 'enumeratorMulti',
          _id: '7f3711fe5bcb2efde166c758',
          validators: [],
          validations: [],
          options: 'owner,admin,staff,customer',
          relation: { type: null, name: null },
          label: 'Role',
          placeholder: 'customer, employee, admin',
        },
        {
          validators: [],
          name: 'wallets',
          type: 'relation',
          _id: 'ebed2ca23c6cc7f44afff397',
          validations: [],
          relation: { type: 'otm', name: 'wallet' },
          label: 'Wallets',
        },
        {
          validators: [],
          name: 'transactions',
          type: 'relation',
          _id: '16dfc8bb206be2feaa2c6f04',
          validations: [],
          relation: { type: 'otm', name: 'transaction' },
          label: 'Transactions',
        },
        {
          name: 'age',
          type: 'integer',
          _id: 'dcb9b448e5bce7c8bdea1ece',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Age',
          placeholder: '18',
        },
        {
          name: 'owner',
          type: 'boolean',
          _id: 'd3acf997e55592abc2c774d1',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          placeholder: 'true',
          label: 'Owner',
        },
        {
          valid: false,
          validators: [],
          validations: [],
          name: 'messages',
          type: 'relation',
          _id: '5df7f9807cf4d62f17b0b9af',
          relation: { type: 'otm', name: 'message' },
          label: 'Messages',
        },
        { name: '_id', type: 'string', _id: '5f6ab0bbfb54cf51242ddb6a', validators: [], validations: [], label: '_id' },
      ],
    },
    {
      _id: '9bb6eaefd16bcaadbadb6064',
      name: 'wallet',
      plural: 'wallets',
      label: 'Wallet',
      pluralL: 'Wallets',
      attributes: [
        { name: '_id', type: 'string', _id: '3a1fa3ceb681ccd0bfa9ffbf', validators: [], validations: [], label: '_id' },
        {
          validators: [],
          name: 'user',
          type: 'relation',
          _id: 'ebed2ca23c6cc8f44afff397',
          validations: [],
          relation: { type: 'mto', name: 'user' },
          label: 'User',
          placeholder: 'john@gmail.com',
        },
        {
          validators: [],
          name: 'balance',
          type: 'decimal',
          _id: '1fcb66bc9bfffdff5cb2a4d0',
          validations: [],
          relation: { type: null, name: null },
          label: 'Balance',
          placeholder: '$88,888',
        },
        {
          validators: [],
          name: 'transactions',
          type: 'relation',
          relation: { type: 'otm', name: 'transaction' },
          _id: '3fbbaa1f2f3b78c1cc6e8930',
          validations: [],
          label: 'Transactions',
        },
      ],
    },
    {
      _id: 'dc01d49b61bcb3208597d9e1',
      name: 'transaction',
      plural: 'transactions',
      label: 'Transaction',
      pluralL: 'Transactions',
      attributes: [
        { name: '_id', type: 'string', _id: 'b8eccaecb1ac1e8725efec2b', validators: [], validations: [], label: '_id' },
        {
          validators: [],
          name: 'amount',
          type: 'decimal',
          _id: 'f66fd03735b45cad81d42d88',
          validations: [],
          relation: { type: null, name: null },
          label: 'Amount',
        },
        {
          validators: [],
          name: 'status',
          type: 'enumerator',
          options: 'processing,complete,declined,cancelled,rejected',
          _id: '0ec5c1e2cfbb99fe37a844e7',
          validations: [],
          relation: { type: null, name: null },
          label: 'Status',
          placeholder: 'processing,complete,declined,cancelled,rejected',
        },
        {
          validators: [],
          name: 'chargeDate',
          type: 'dateTime',
          _id: 'b5b16d729dbbd5e6c87807be',
          validations: [],
          relation: { type: null, name: null },
          label: 'Charge Date',
          placeholder: '12/02/23',
        },
        {
          validators: [],
          name: 'description',
          type: 'string',
          _id: 'dbcd9fd9b6e64f52f07bf8dc',
          validations: [],
          relation: { type: null, name: null },
          label: 'Description',
          placeholder: 'Description...',
        },
        {
          validators: [],
          name: 'user',
          type: 'relation',
          relation: { type: 'mto', name: 'user' },
          _id: 'a51f1f44e1bcb61b32d3bdcc',
          validations: [],
          label: 'User',
          placeholder: 'User...',
        },
        {
          validators: [],
          name: 'wallet',
          type: 'relation',
          relation: { type: 'mto', name: 'wallet' },
          _id: 'acff83fa7aeae96c6d0b7a1c',
          validations: [],
          label: 'Wallet',
        },
      ],
    },
    {
      _id: '57dbd2eb064c0d1ac7fc47a',
      name: 'strategy',
      plural: 'strategies',
      label: 'Strategy',
      pluralL: 'Strategies',
      attributes: [],
    },
    {
      _id: '57dbd2eb064c2d9ac7fc47a4',
      name: 'asset',
      plural: 'assets',
      label: 'Asset',
      pluralL: 'Assets',
      attributes: [],
    },
    {
      _id: '57dbd2eb064c2d9ac7fc47a4',
      name: 'new',
      plural: 'news',
      label: 'New',
      pluralL: 'News',
      attributes: [],
    },
    {
      _id: '57dbd2eb034c0d9ac7fc47a4',
      name: 'chat',
      plural: 'chats',
      label: 'Chat',
      pluralL: 'Chats',
      attributes: [],
    },
    {
      _id: '57dbd2eb064c4d9ac7fc47a4',
      name: 'chatUser',
      plural: 'chatUsers',
      label: 'ChatUser',
      pluralL: 'ChatUsers',
      attributes: [],
    },
    {
      _id: '57dbd2eb064c5d9ac7fc47a4',
      name: 'chatMessage',
      plural: 'chatMessages',
      label: 'ChatMessage',
      pluralL: 'ChatMessages',
      attributes: [
        {
          _id: '578595c0b641fd6583b42f78',
          name: 'body',
          type: 'string',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Body',
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          relation: { type: 'mto', name: 'user' },
          name: 'user',
          _id: '23da767f77e3c87f05df80ce',
          label: 'User',
        },
      ],
    },
    {
      _id: '51dbd2eb064c4d9ac7fc47a4',
      name: 'notification',
      plural: 'notifications',
      label: 'Notification',
      pluralL: 'Notifications',
      attributes: [],
    },
    {
      _id: '22dbd2eb064c4d9ac7fc47a4',
      name: 'referral',
      plural: 'referrals',
      label: 'Referral',
      pluralL: 'Referrals',
      attributes: [],
    },
  ],
}
