export const FooBars = {
  server: 'nuxt',
  mobile: 'flutter',
  fbDev: {},
  fbProd: {},
  entities: [
    {
      name: 'foo',
      label: 'Foo',
      plural: 'foos',
      pluralL: 'Foos',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'fooBoolean',
          label: 'Foo Boolean',
          _id: '6dcc79ee7eb4f14dc1e0ce4b',
          placeholder: 'foo boolean placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'fooString',
          label: 'Foo String',
          _id: '3d00e44df2b3bb22da6723cb',
          placeholder: 'foo string placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'fooText',
          label: 'Foo Text',
          _id: 'bcbbfc4c1547d1627cd15fe2',
          placeholder: 'foo text placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'fooInteger',
          label: 'Foo Integer',
          _id: '25baeb5cb6b90eb3dd68ce9d',
          placeholder: 'foo integer placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'fooDecimal',
          label: 'Foo Decimal',
          _id: 'b0dc5b861bf1cccdffa63ae4',
          placeholder: 'foo decimal placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'date',
          name: 'fooDate',
          label: 'Foo Date',
          _id: 'ad24804ffbd5a7932701d5f1',
          placeholder: 'foo date placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'fooDateTime',
          label: 'Foo Date Time',
          _id: '10ebc11ec20a1cac1e1abdfe',
          placeholder: 'foo datetime placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'fooArray',
          label: 'Foo Array',
          _id: '2acf20585fe9beac06d823d8',
          placeholder: 'foo array placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'map',
          name: 'fooMap',
          label: 'Foo Map',
          _id: '6fbadff36a541a3730eceabc',
          placeholder: 'foo map placeholder',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'fooEnumerator',
          label: 'Foo Enumerator',
          _id: 'df3dab2f94babfb3eb2decef',
          placeholder: 'a,b,c,',
          relation: { name: null, type: '' },
          options: 'a,b,c',
        },
        {
          validators: [],
          validations: [],
          type: 'enumeratorMulti',
          name: 'foodEnumeratorMulti',
          label: 'Foo Enum Multi',
          _id: 'd35baeae0fdea2f0aaba41ad',
          placeholder: 'a,b,c',
          relation: { name: null, type: '' },
          options: 'a,b,c',
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'fooOTM',
          label: 'Foo OTM',
          _id: '3b91bb9236bf6ae409babfed',
          placeholder: 'one-to-many',
          relation: { name: 'related', type: 'otm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'fooMTO',
          label: 'Foo MTO',
          _id: 'cb9e4df7b51061a10b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'related', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'fooOTO',
          label: 'Foo OTO',
          _id: '9ba3dbf02fd484ec618a9e8f',
          placeholder: 'one-to-one',
          relation: { name: 'related', type: 'oto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'fooMTM',
          label: 'Foo MTM',
          _id: 'ec2ef0ec3cd71cfecabfbcd4',
          placeholder: 'many-to-many',
          relation: { name: 'related', type: 'mtm' },
        },
      ],
      _id: '8c5a8f9659e0f926cf0da3ff',
    },
  ],
}
