export const Hotel = {
  server: 'nuxt',
  mobile: 'flutter',
  fbDev: {},
  fbProd: {},
  entities: [
    {
      _id: 'fb80c35deae8c1d25f4acbbd',
      name: 'user',
      plural: 'users',
      label: 'User',
      pluralL: 'Users',
      attributes: [
        {
          name: 'status',
          type: 'enumerator',
          _id: '077cb5ead63ef967d1adcc2c',
          validators: [],
          validations: [],
          options: 'pending, active, closed',
          relation: { type: null, name: null },
          label: 'Status',
          placeholder: 'pending,open,closed',
        },
        {
          name: 'email',
          type: 'string',
          _id: '0ca1c138ce4ddacdcbbc49d6',
          validators: ['email', 'unique'],
          validations: [],
          relation: { type: null, name: null },
          label: 'Email',
          placeholder: 'john@email.com',
        },
        {
          name: 'firstName',
          type: 'string',
          _id: '5aab0a1efa84976ab3afea9e',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'First Name',
          placeholder: 'John',
        },
        {
          name: 'lastName',
          type: 'string',
          _id: '040e9eeeec2ae4eb4fd1946e',
          validators: [],
          validations: [],
          relation: { type: null, name: null },
          label: 'Last Name',
          placeholder: 'Doe ',
        },
        {
          name: 'role',
          type: 'enumeratorMulti',
          _id: '7f3711fe5bcb2efde166c758',
          validators: [],
          validations: [],
          options: 'owner,admin,staff,customer',
          relation: { type: null, name: null },
          label: 'Role',
          placeholder: 'customer, employee, admin',
        },
        { name: '_id', type: 'string', _id: '5f6ab0bbfb54cf51242ddb6a', validators: [], validations: [], label: '_id' },
        {
          validators: [],
          validations: [],
          name: 'tag',
          _id: 'aea62adb777aefdbbc39b7fb',
          relation: { type: null, name: null },
          type: 'enumeratorMulti',
          options: 'bronze, silver, gold, platinum, diamond',
        },
      ],
    },
    {
      name: 'hotel',
      label: 'Hotel',
      plural: 'hotels',
      pluralL: 'Hotelss',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          label: 'name',
          _id: '197ff0eaef4daed141ec6304',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'stars',
          label: 'stars',
          _id: 'ec45ed014fea01618777eed8',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'caption',
          label: 'caption',
          _id: '1bd8d23aca500dda598acb38',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'rating',
          label: 'rating',
          _id: 'e4f1f7ecbda9ce7df47870ec',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'urlWebsite',
          label: 'urlWebsite',
          _id: 'a86a8ddc599ebd83ee4f6a6c',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'phone',
          label: 'phone',
          _id: 'f7f9ba463b3471d438bfd5a8',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'email',
          label: 'email',
          _id: 'b17710e371c7b62dec4dbdab',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'types',
          label: 'types',
          _id: '6b0e60ed63ff955bbc93e1ae',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'location',
          label: 'location',
          _id: 'fb1ccff0aaaedf4036ffabad',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'geoAddress',
          label: 'geoAddress',
          _id: '527fdfe019d4beebfdd63cbf',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'geoCity',
          label: 'geoCity',
          _id: '680b4051ba76cbb49ad3a3ae',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'geoCountry',
          label: 'geoCountry',
          _id: '26dbec9d5538e8dddfecc4ab',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'geoLat',
          label: 'geoLat',
          _id: 'eea3c849de0dda7c1b8bf1c8',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'geoLong',
          label: 'geoLong',
          _id: '6ebec4ad6ce2472e2321ee2b',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'urlsImgThumbs',
          label: 'urlsImgThumbs',
          _id: 'e57bab2fd5c43f59f3abef4e',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'urlsImgCovers',
          label: 'urlsImgCovers',
          _id: '1f89eb2417048077976b79c3',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'urlsImgPhotos',
          label: 'urlsImgPhotos',
          _id: 'e2403bdd434e0eea9256b6a5',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'reasonsToBook',
          label: 'reasonsToBook',
          _id: 'b66d8df4eb0cd1173a1bfbb2',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'reasonsToBookTop',
          label: 'reasonsToBookTop',
          _id: '36346cfbcf1daf5fb7cf7b19',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'ratingCount',
          label: 'ratingCount',
          _id: 'bb24606ceda7a1c3e1b6bce5',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'ratingsScore',
          label: 'ratingsScore',
          _id: 'e0ad18a66a33c6a8dad4a309',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'ratingsScoreLocation',
          label: 'ratingsScoreLocation',
          _id: '5c2ffcb1dad5cda96e2e2dcd',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'ratings',
          label: 'ratings',
          _id: '0e45ba6ff6eb6eefc37bb9ee',
          placeholder: '',
          relation: { name: null, type: 'otm' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'rooms',
          label: 'rooms',
          _id: 'efda893b9f6544f7aa1aec9e',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'amenities',
          label: 'amenities',
          _id: '1dea552aceae6bc2f15fe29f',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'meta',
          label: 'meta',
          _id: '3afa3ef7ad2b3ac0816effbd',
          placeholder: '',
          relation: { name: null, type: '' },
        },
      ],
      _id: 'c2cbe05f350daaac6a4367cc',
    },
    {
      name: 'room',
      label: 'Room',
      plural: 'rooms',
      pluralL: 'Roomss',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'hotelId',
          label: 'hotelId',
          _id: '1e7402ad03e52c568afb88ed',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'roomNumber',
          label: 'roomNumber',
          _id: 'efcdf9dfbf8c6baaba9302ce',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'type',
          label: 'type',
          _id: '9afae2d9d34c5810a4ccace9',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'description',
          label: 'description',
          _id: '02271adc3049df33ff7b7a6a',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'pricePerNight',
          label: 'pricePerNight',
          _id: 'bdcc0d1a76af8eff6d4fb493',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'priceDiscounted',
          label: 'priceDiscounted',
          _id: 'b8a48888367e21c7b0c7c7c2',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'availability',
          label: 'availability',
          _id: '27ff4fcc7107ecb6adac7c46',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'capacity',
          label: 'capacity',
          _id: 'e27facfaf898c847dc0fd85e',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumeratorMulti',
          name: 'amenities',
          label: 'amenities',
          _id: 'adadaa657e359fe87ddc6d9e',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'floor',
          label: 'floor',
          _id: '2b4be1bfd6d95ba0d0c0eedb',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'imgUrlsThumbnail',
          label: 'imgUrlsThumbnail',
          _id: 'adcafa771c5747b1bdf34af2',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'imgUrlsCover',
          label: 'imgUrlsCover',
          _id: 'e8b70bcffccaecade99eb526',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'imgUrlsPhoto',
          label: 'imgUrlsPhoto',
          _id: '923d2b3d440c7313d9d894ce',
          placeholder: '',
          relation: { name: null, type: '' },
        },
      ],
      _id: 'deafaf44de1ed037d73e1893',
    },
    {
      name: 'booking',
      label: 'Booking',
      plural: 'bookings',
      pluralL: 'Bookings',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'hotelId',
          label: 'hotelId',
          _id: 'f5a78d6ac0de8f4fb4dfaa61',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'userId',
          label: 'userId',
          _id: 'ef8cd0fdcd8bc589dbf732a0',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'roomId',
          label: 'roomId',
          _id: 'd0d05fbd530055ed263138be',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'enumerator',
          name: 'status',
          label: 'status',
          _id: 'ca66fbfe4ecc4af1d76531d3',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'dateStart',
          label: 'dateStart',
          _id: '2b78ebea629addadbdbcb77f',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'dateEnd',
          label: 'dateEnd',
          _id: '0d3d0da5deccfd051dc3d0eb',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'priceSubTotal',
          label: 'priceSubTotal',
          _id: 'bbbcaf1cbb1c5e0fe7eb08ef',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'priceTaxes',
          label: 'priceTaxes',
          _id: 'd4db70aacd0cbfb4ccb1a0d7',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'priceFees',
          label: 'priceFees',
          _id: 'ea0befaacec7e3defcaf50bc',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'priceDiscounts',
          label: 'priceDiscounts',
          _id: 'cbbf6c7ffed3b411dbc9bea3',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'priceTotal',
          label: 'priceTotal',
          _id: 'ded1eed93df0d40c6465a381',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'guests',
          label: 'guests',
          _id: '1b69148ba454dae8ab0deb15',
          placeholder: '',
          relation: { name: null, type: '' },
        },
      ],
      _id: '1ffe541a3e16cf13ebed5d54',
    },
    {
      name: 'review',
      label: 'Review',
      plural: 'reviews',
      pluralL: 'Reviews',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'userId',
          label: 'userId',
          _id: 'a97a6b3e6f3cbfcd55d51f7b',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'roomId',
          label: 'roomId',
          _id: '7066e3ccc7b45c7a7b9adcbe',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'hotelId',
          label: 'hotelId',
          _id: 'c80c145ba47ca332a5c2723f',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'body',
          label: 'body',
          _id: 'd35ad6da4c2f02dac8a42d00',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'rating',
          label: 'rating',
          _id: '7cf0a2eded208dadbda31ffe',
          placeholder: '',
          relation: { name: null, type: '' },
        },
      ],
      _id: '97cb59d8adc93a1acdf8abc1',
    },
  ],
}
