export const LeetCode = {
  server: 'nuxt',
  mobile: 'flutter',
  fbDev: {},
  fbProd: {},
  entities: [
    {
      _id: 'fb80c35deae8c1d25f4acbbd',
      name: 'user',
      plural: 'users',
      label: 'User',
      pluralL: 'Users',
      attributes: [
        {
          name: '_id',
          type: 'text',
          _id: '5f6ab0bbfb54cf51242ddb6a',
          validators: [],
          validations: [],
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'email',
          label: 'email',
          _id: '0cadf0cb95bd08874aeb398e',
          placeholder: '',
          relation: { name: null, type: '' },
        },
        {
          name: 'firstName',
          type: 'string',
          _id: '5aab0a1efa84976ab3afea9e',
          validators: [],
          validations: [],
          relation: { name: null, type: '' },
        },
        {
          name: 'lastName',
          type: 'string',
          _id: '040e9eeeec2ae4eb4fd1946e',
          validators: [],
          validations: [],
          relation: { name: null, type: '' },
        },
        {
          name: 'age',
          type: 'integer',
          _id: 'dcb9b448e5bce7c8bdea1ece',
          validators: [],
          validations: [],
          relation: { name: null, type: '' },
        },
        {
          name: 'status',
          type: 'enumerator',
          _id: '077cb5ead63ef967d1adcc2c',
          validators: [],
          validations: [],
          options: 'open,closed,pending',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          name: 'avatarUrl',
          _id: '7cb7838708b53d78de6bfdee',
          relation: { type: null, name: null },
          type: 'string',
        },
        {
          validators: [],
          validations: [],
          name: 'city',
          _id: 'a3aef9ecb114efde29c0aed6',
          relation: { type: null, name: null },
          type: 'string',
        },
        {
          validators: [],
          validations: [],
          name: 'country',
          _id: 'fdbd3ba3d4f1bbbbc7cfcfca',
          relation: { type: null, name: null },
          type: 'string',
        },
        {
          validators: [],
          validations: [],
          name: 'dob',
          _id: 'dae869bbcacb1ba1defc6ae1',
          relation: { type: null, name: null },
          type: 'date',
        },
        {
          validators: [],
          validations: [],
          name: 'status',
          _id: 'deaa69fd5793cf29f62da810',
          relation: { type: null, name: null },
          type: 'enumerator',
          options: 'pending,active,closed,deactivated,blocked',
        },
        {
          validators: [],
          validations: [],
          name: 'username',
          _id: 'c16ee76ee14ce9f8c818dca3',
          relation: { type: null, name: null },
          type: 'string',
        },
      ],
    },
    {
      _id: '59abcbce7aeedbbcd15d90b13',
      name: 'article',
      label: 'Article',
      plural: 'articles',
      pluralL: 'Articles',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'type',
          label: 'Type',
          _id: 'b2f7ba1d54e96e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'title',
          label: 'Title',
          _id: 'b2f7ba1d54e96efde143eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'caption',
          label: 'Caption',
          _id: 'b2f7ba1d54e96efde313eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'body',
          label: 'Body',
          _id: 'b2f7ba1d54e96efde213eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'link',
          label: 'Link',
          _id: 'b2f7ba1d54e96efd1e13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'urlCoverImg',
          label: 'Cover Img',
          _id: 'b2f7ba1d54e96ef8de13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'urlVideo',
          label: 'Video',
          _id: 'b2f7ba1d54e96efd7e13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'language',
          label: 'Language',
          _id: 'b2f7ba1d54e966efde13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'numComments',
          label: '# Comments',
          _id: 'b2f7ba1d54e96ef5de13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'numVotes',
          label: '# Votes',
          _id: 'b2f7ba1d54e496efde13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isPublished',
          label: 'Published?',
          _id: 'b2f7ba1d54e963efde13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isOriginal',
          label: 'Original?',
          _id: 'b2f7ba1d54e962efde13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'author',
          label: 'Author',
          _id: 'cb9e4df71b51061a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'comments',
          label: 'Comments',
          _id: 'cb9e4df711521061a110b22ba8c',
          placeholder: 'one-to-many',
          relation: { name: 'related', type: 'otm' },
        },
      ],
    },
    {
      _id: '59abcbce73aeedbbcd151d90b13',
      name: 'badge',
      label: 'Badge',
      plural: 'Badges',
      pluralL: 'badges',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d5242e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          _id: 'b2f7ba111d542e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'urlImg',
          _id: 'b2f7ba111d542961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'year',
          _id: 'b2f7ba111d52e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'month',
          _id: 'b2f7ba111d54e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
      ]
    },
    {
      _id: '59abcbce73aeedbbcd151d910b13',
      name: 'badgeItem',
      label: 'BadgeItem',
      plural: 'BadgeItems',
      pluralL: 'badgesItems',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d52422e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'date',
          name: 'date',
          _id: 'b2f7ba111d5342e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'month',
          _id: 'b2f7ba111d35342e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'year',
          _id: 'b2f7ba1112d5342e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'user',
          label: 'User',
          _id: 'cb9e41f71b51061a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
      ]
    },
    {
      _id: '59abcbce7aeedbb3cd151d90b13',
      name: 'comment',
      label: 'Comment',
      plural: 'comments',
      pluralL: 'Comments',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d542e2961e1fde1113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'body',
          _id: 'b2f7ba11d5142961e12fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'code',
          _id: 'b2f7ba11d5142961e12fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'user',
          label: 'User',
          _id: 'cb9e41f71b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'post',
          label: 'Post',
          _id: 'cbe41f71b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'post', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'article',
          label: 'Article',
          _id: 'cb941f71b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'article', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'comment',
          label: 'Comment',
          _id: 'cb91e41f71b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'comment', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'comments',
          label: 'Comments',
          _id: 'cb91e41f71b51612a101b22ba8c',
          placeholder: 'one-to-many',
          relation: { name: 'comment', type: 'otm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'problem',
          label: 'Problem',
          _id: 'cb1e41f71b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'problem', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'submission',
          label: 'Submission',
          _id: 'cb9e41f71b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'submission', type: 'mto' },
        },
      ]
    },
    {
      _id: '59abcbce7aeedbbcd151d190b13',
      name: 'company',
      label: 'Company',
      plural: 'companies',
      pluralL: 'Companies',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d542e9611e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          _id: 'b2f7ba11d542e9621e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'industry',
          _id: 'b2f7ba11d542e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'founded',
          _id: 'b2f7ba11d542e962e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'location',
          _id: 'b2f7ba11542e962e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'urlAvatar',
          _id: 'b2f7ba11d52e962e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'int',
          name: 'teamSize',
          _id: 'b2f7ba11d52e962e1de113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'industries',
          _id: 'b2f7ba11d52e962ede113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'founders',
          _id: 'b2f7ba11d52e92ede113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'technologies',
          _id: 'b2f7ba11d52e9621de113eb8cz',
          relation: { name: null, type: '' },
        },
      ]
    },
    {
      _id: '59abcbce7aeedbbcd1521d90b13',
      name: 'job',
      label: 'Job',
      plural: 'jobs',
      pluralL: 'Jobs',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'string',
          name: '_id',
          _id: 'b2f7ba1d542e9621e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'title',
          _id: 'b2f7ba11d5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'caption',
          _id: 'p2f7ba11d5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'location',
          _id: 'b2f7ba11d5421e961e1fde113eg8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'type',
          _id: 'b2f7ba11d5521e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'description',
          _id: 'b2f7bq11d5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'experience',
          _id: 'b2f7bb11d5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'project',
          _id: 'b217ba11d5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'requirements',
          _id: 'b2f71ba11d5421se961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'whoAreYou',
          _id: 'b2f7b1a11d5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'equity',
          _id: 'b2f7ba11d5421e9611e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'benefits',
          _id: 'b2f17ba11d5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isRemote',
          _id: 'b2f17ba11w5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'technologies',
          _id: 'b2f17ba11d5421e96qe1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'company',
          label: 'Company',
          _id: 'cbe41f71b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'company', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'user',
          label: 'User',
          _id: 'dbe41f71b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
      ]
    },
    {
      _id: '59abcbce7aeedbbcd1511d90b13',
      name: 'contest',
      label: 'Contest',
      plural: 'contests',
      pluralL: 'Contests',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d542e9611e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          _id: 'b2f7ba11d5242e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'body',
          _id: 'b2f7ba11d5242e61e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'title',
          _id: 'b2f7ba11d5242e961e1fd113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'company',
          label: 'Company',
          _id: 'cbe41f71b510612aa01b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'company', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'sponsor',
          label: 'Sponsor',
          _id: 'cbe41fa1b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'sponsor', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'timeStart',
          _id: 'b2f7ba111d5342e961e1fde113ez8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'timeEnd',
          _id: 'b2f7ba111d5342e961e1fda113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'problem',
          label: 'Problems',
          _id: 'cbe41fa1b51612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'problem', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'submissions',
          label: 'Submissions',
          _id: 'cbe4fa1b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'submissions', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'participants',
          label: 'Participants',
          _id: 'cbe41f1b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'participants', type: 'mto' },
        },
      ]
    },
    {
      _id: '59abcbce7aeedb1bcd151d90b13',
      name: 'participant',
      label: 'Participant',
      plural: 'participants',
      pluralL: 'Participants',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d5242e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          _id: 'b2f7ba111d542e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'contest',
          label: 'Contest',
          _id: 'abe41f1b510612a101b22ba8c',
          placeholder: 'one-to-many',
          relation: { name: 'contest', type: 'otm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'user',
          label: 'User',
          _id: 'abe41f1b510612a101b22ba8d',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'submission',
          label: 'Submissions',
          _id: 'cbe4fa1b510612a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'submissions', type: 'mto' },
        },
        {
          name: 'score',
          type: 'integer',
          _id: 'dcb9b448e15bce7c8bdea1ece',
          validators: [],
          validations: [],
          relation: { name: null, type: '' },
        },
        {
          name: 'rank',
          type: 'integer',
          _id: 'dcb9b448e25bce7c8bdea1ece',
          validators: [],
          validations: [],
          relation: { name: null, type: '' },
        },
        {
          name: 'rating',
          type: 'integer',
          _id: 'dcb9b4483e5bce7c8bdea1ece',
          validators: [],
          validations: [],
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'time',
          _id: 'b2f7ba111d5342e961e1fde113ez8cz',
          relation: { name: null, type: '' },
        },
      ]
    },
    {
      _id: '59abcbce7aeed2bbcd151d90b13',
      name: 'guide',
      label: 'Guide',
      plural: 'guides',
      pluralL: 'Guides',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d1542e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          _id: 'b2f7ba11d25452e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'title',
          _id: 'b2f7ba11d25442e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'body',
          _id: 'b2f7ba11d25432e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'caption',
          _id: 'b2f7ba11d25422e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'description',
          _id: 'b2f7ba11d25142e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'topics',
          _id: 'b2f1ba11d25142e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
      ]
    },
    {
      _id: '59abcbce7ae1edbbcd151d90b13',
      name: 'notification',
      label: 'Notification',
      plural: 'notifications',
      pluralL: 'Notifications',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7bb1d5421e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'title',
          _id: 'b2f7ba11d5422e961e11de113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'body',
          _id: 'b5f7ba11d5422e961e11de113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'type',
          _id: 'b2f7ba11d5422e961e11de113ep8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'int',
          name: 'points',
          _id: 'b2f7ba11d5422e961e11de113ep8co',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isPublished',
          _id: 'b2f7ba11d5422e961e11de413ep8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'date',
          name: 'date',
          _id: 'b2f7ba11d542e961e11de113ep8cz',
          relation: { name: null, type: '' },
        },
      ]
    },
    {
      _id: '59abcbce7aeed1bbcd151d90b13',
      name: 'notificationItem',
      label: 'NotificationItem',
      plural: 'notificationItems',
      pluralL: 'NotificationItems',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d5242e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'icon',
          _id: 'b2f7ba1111d542e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isRead',
          _id: 'b2f7ba111d542e2961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'points',
          _id: 'b2f7ba111d542e9631e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'date',
          _id: 'b2f7ba111d542e9614e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'notifiableId',
          _id: 'b2f7ba111d542e9615e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'notifiableType',
          _id: 'b2f7ba111d542e961e61fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'type',
          _id: 'b2f7ba111d542e961e1fde7113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'notification',
          _id: 'b2f7ba111d542e961e1f8de113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'user',
          label: 'User',
          _id: 'cb9e41f71b51061a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
      ]
    },
    {
      _id: '59abcbce7aeed2bbcd151d90b13',
      name: 'post',
      label: 'Post',
      plural: 'posts',
      pluralL: 'Posts',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'string',
          name: '_id',
          _id: 'b2f7ba1d542e1961e1fdde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'title',
          _id: 'b2f7ba11d5432e961ez1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'body',
          _id: 'q2f7ba11d5432e961ez1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isPublished',
          _id: 'q2f7ba11d5432e961ez1fde113eb8qq',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'numVotes',
          _id: 'q217ba11d5432e961ez1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'numViews',
          _id: 'q2f2ba11d5432e961ez1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'numComments',
          _id: 'q2f7ba11d3432e961ez1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'dateTime',
          name: 'submitted',
          _id: 'q2f7ba11d5432e961ez1fde113eb8qz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'user',
          label: 'User',
          _id: 'cb9e41f71b5106c1a101b22ba8c',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'comments',
          label: 'Comments',
          _id: 'cb9e41f71b51061ba101b22ba8c',
          placeholder: 'one-to-many',
          relation: { name: 'comment', type: 'otm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'topics',
          label: 'Topics',
          _id: 'cb9e41f71b51061a10a1b22ba8c',
          placeholder: 'one-to-many',
          relation: { name: 'topic', type: 'otm' },
        },
      ]
    },
    {
      _id: '59abcbce7aeedbb2cd151d90b13',
      name: 'problem',
      label: 'Problem',
      plural: 'problems',
      pluralL: 'Problems',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d5412e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'title',
          _id: 'b2f7ba113d542e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'body',
          _id: 'b2f7ba113d542e961e1fde13eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'frequency',
          _id: 'b2f7ba113d542e961e1fde113e8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'difficulty',
          _id: 'b2f7ba113d542e91e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'author',
          label: 'Author',
          _id: 'cb9e41f71b5106c1a101b22ba8z',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isPublished',
          _id: 'q2f7ba11d5432e961ez1fde113eb8q1',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isSubmitted',
          _id: 'q2f7ba11d5432e961ez1fde1132b8qq',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'numLC',
          _id: 'q2f7ba11d5432e961ez1fde113eb8zq',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'editorialAuthor',
          label: 'Editor',
          _id: 'db9e41f71b5106c1a1x1b22ba8z',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'editorialBody',
          _id: 'b2f7ba113d542e91e1fde113qb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'editorialRating',
          _id: 'b2f7ba113d542e91e1fde113eb8co',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'editorialVotes',
          _id: 'z2f7ba113d542e91e1fde113eb8co',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'accepted',
          _id: 'z2f7ba113d542e91e1fde113ec8co',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'submissions',
          _id: 'z2f7ba113d542e91e1fde113eb8xo',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'acceptanceRate',
          _id: 'z2f7ba113d542e91e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'testSuite',
          _id: 'z2f7ba113d542e91e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'topics',
          label: 'Topics',
          _id: 'cb9e41f71b5106c1a101b22baxc',
          relation: { name: 'topic', type: 'mtm' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'hints',
          label: 'Hints',
          _id: 'db9e41f71b5106c1a101b22ba8c',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'constraints',
          label: 'Constraints',
          _id: 'db9e41f71b5106c1a101b22ba89',
          relation: { name: null, type: '' },
        },
      ]
    },
    {
      _id: '59abcbce7ae2edbzcd151d90zb13',
      name: 'submission',
      label: 'submission',
      plural: 'submissions',
      pluralL: 'Submissions',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d542e1961e1fde113eb8zcz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'body',
          _id: 'b2f7za11d5412e961e1fde113eb8czz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'title',
          _id: 'b2f7ba21d5412e961e1fde113eb8czz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'explanation',
          _id: 'b2f7ba11d5412e961e2fde113eb8czz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'language',
          _id: 'b2f7ba11d5412e961e1fde113e38czz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'text',
          name: 'notes',
          _id: 'h2f7ba11d5412e961e1fde113xb8czz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'user',
          label: 'User',
          _id: 'db9e41f7e1b5106c1a1x1b22ba8x',
          placeholder: 'many-to-one',
          relation: { name: 'user', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'problem',
          label: 'Problem',
          _id: 'db9e41f71b5106csa1x1b22ba8z',
          placeholder: 'many-to-one',
          relation: { name: 'problem', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'contest',
          label: 'Contest',
          _id: 'db9e41f71b5106c1a1t1b22ba8z',
          placeholder: 'many-to-one',
          relation: { name: 'contest', type: 'mto' },
        },
        {
          validators: [],
          validations: [],
          name: 'timeSubmitted',
          label: 'Submit Time',
          _id: 'dae869bbcacb1ba1defc6ae1',
          relation: { type: null, name: null },
          type: 'dateTime',
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isPublished',
          label: 'Published?',
          _id: 'b2f7ba1d54e963cfde13eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isShared',
          label: 'Shared?',
          _id: 'b2f7ba1d54ex63efde13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'boolean',
          name: 'isContest',
          label: 'Contest?',
          _id: 'b2f7ba1dz4e963efde13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'penalty',
          label: 'Penalty',
          _id: 'b2f7ba1dp4e963efde13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'numVotes',
          label: '# Votes',
          _id: 'b2f7ba1dp4e963efde13ex8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'integer',
          name: 'numComments',
          label: '# Comments',
          _id: 'b2f7ba1dp4e963ecde13eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'runTime',
          label: 'Run Time',
          _id: 'b2f7ba1dp4e963ecdex3eb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'decimal',
          name: 'beats',
          label: 'Beats',
          _id: 'b2f7ba1dp4e963ecde13cb8ca',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'array',
          name: 'voterIds',
          label: 'VoterIds',
          _id: 'b2f7ba1dp4e963ecde13cb8cb',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'topics',
          label: 'Topics',
          _id: 'cb9e4df711521061a110bx2ba8x',
          placeholder: 'many-to-many',
          relation: { name: 'comment', type: 'mtm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'comments',
          label: 'Comments',
          _id: 'cb9e4df711521061a110b22ba8x',
          placeholder: 'one-to-many',
          relation: { name: 'comment', type: 'otm' },
        },
      ]
    },
    {
      _id: '59abczce7ae2e6dbbcd151d90b13',
      name: 'topic',
      label: 'Topic',
      plural: 'topics',
      pluralL: 'Topics',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d5425e1961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          _id: 'b2f7ba111d5412e5961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'posts',
          label: 'Posts',
          _id: 'cb9e4df7115210641a110b22ba8x',
          placeholder: 'many-to-many',
          relation: { name: 'post', type: 'mtm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'guides',
          label: 'Guides',
          _id: 'cb9e4df7115210631a110b22ba8x',
          placeholder: 'many-to-many',
          relation: { name: 'guide', type: 'mtm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'problems',
          label: 'Problems',
          _id: 'cb9e4df711521061a1120b22ba8x',
          placeholder: 'many-to-many',
          relation: { name: 'problem', type: 'mtm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'contests',
          label: 'Contests',
          _id: 'cb9e4df711521061a110b221ba8x',
          placeholder: 'many-to-many',
          relation: { name: 'contest', type: 'mtm' },
        },
        {
          validators: [],
          validations: [],
          type: 'relation',
          name: 'submissions',
          label: 'submissions',
          _id: 'cb9e4df711521061a110b221ba8x',
          placeholder: 'many-to-many',
          relation: { name: 'submission', type: 'mtm' },
        },
      ]
    },
    {
      _id: '59bbcbce37ae2edbbcd151d90b13',
      name: 'submission',
      label: 'submission',
      plural: 'submissions',
      pluralL: 'Submissions',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba12d542e1961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          _id: 'b2f7ba11d5412e9611e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
      ]
    },
    {
      _id: '59abcbce7ae2edbbcd1351d90b13',
      name: 'submission',
      label: 'submission',
      plural: 'submissions',
      pluralL: 'Submissions',
      attributes: [
        {
          validators: [],
          validations: [],
          type: 'text',
          name: '_id',
          _id: 'b2f7ba1d542e1961e21fde113eb8cz',
          relation: { name: null, type: '' },
        },
        {
          validators: [],
          validations: [],
          type: 'string',
          name: 'name',
          _id: 'b2f7ba11d54112e961e1fde113eb8cz',
          relation: { name: null, type: '' },
        },
      ]
    },
    
  ],
}
