export const User = [
  {
    _id: 'fb80c35deae8c1d25f4acbbz',
    name: 'user',
    plural: 'users',
    label: 'User',
    pluralL: 'Users',
    attributes: [
      {
        name: 'status',
        type: 'enumerator',
        _id: '077cb5ead63ef967d1adcc2z',
        validators: [],
        validations: [],
        options: 'pending,open,closed',
        relation: { type: null, name: null },
        label: 'Status',
        placeholder: 'pending,open,closed',
      },
      {
        name: 'standing',
        type: 'enumerator',
        _id: '077cb5ead63ef967d1adcc2z',
        validators: [],
        validations: [],
        options: 'current,behind',
        relation: { type: null, name: null },
        label: 'Standing',
        placeholder: 'current,behind',
      },
      {
        name: 'email',
        type: 'string',
        _id: '0ca1c138ce4ddacdczbc49d6',
        validators: ['email', 'unique'],
        validations: [],
        relation: { type: null, name: null },
        label: 'Email',
        placeholder: 'john@email.com',
      },
      {
        name: 'firstName',
        type: 'string',
        _id: '5aab0a1efa84976zb3afea9e',
        validators: [],
        validations: [],
        relation: { type: null, name: null },
        label: 'FirstName',
        placeholder: 'John',
      },
      {
        name: 'lastName',
        type: 'string',
        _id: '040z9eeeec2ae4eb4fd1946e',
        validators: [],
        validations: [],
        relation: { type: null, name: null },
        label: 'LastName',
        placeholder: 'Doe ',
      },
      {
        name: 'role',
        type: 'enumeratorMulti',
        _id: '7f3711fe5bcb2efde166z758',
        validators: [],
        validations: [],
        options: 'owner,admin,staff,customer',
        relation: { type: null, name: null },
        label: 'Role',
        placeholder: 'customer, employee, admin',
      },
      {
        validators: [],
        name: 'accounts',
        type: 'relation',
        _id: 'ebed2ca23c6cc7f44zfff397',
        validations: [],
        relation: { type: 'otm', name: 'account' },
        label: 'Accounts',
      },
      {
        validators: [],
        name: 'transactions',
        type: 'relation',
        _id: '16dfc8bb206be2feaa2z6f04',
        validations: [],
        relation: { type: 'otm', name: 'transaction' },
        label: 'Transactions',
      },
      {
        validators: [],
        name: 'banks',
        type: 'relation',
        _id: 'z6db8ffc08aaed0ee2c9d8ce',
        validations: [],
        relation: { type: 'otm', name: 'bank' },
        label: 'Banks',
      },
      {
        name: 'age',
        type: 'integer',
        _id: 'zcb9b448e5bce7c8bdea1ece',
        validators: [],
        validations: [],
        relation: { type: null, name: null },
        label: 'Age',
        placeholder: '18',
      },
      {
        name: 'owner',
        type: 'boolean',
        _id: 'z3acf997e55592abc2c774d1',
        validators: [],
        validations: [],
        relation: { type: null, name: null },
        placeholder: 'true',
        label: 'Owner',
      },
      {
        validators: [],
        name: 'netWorth',
        type: 'decimal',
        _id: '6f5bzab03b55eedac8e92a38',
        validations: [],
        relation: { type: null, name: null },
        label: 'NetWorth',
        placeholder: '$88,888,888',
      },
      {
        valid: false,
        validators: [],
        validations: [],
        name: 'messages',
        type: 'relation',
        _id: '5df7f9807cf4d62f17b0b9az',
        relation: { type: 'otm', name: 'message' },
        label: 'Messages',
      },
      { name: '_id', type: 'string', _id: '5f6ab0bbfb54cf51242ddb6z', validators: [], validations: [], label: '_id' },
    ],
  },
]
