name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - uses: eriknyk/increment-variable-action@v1.0.0
        name: Bump Version Code
        with:
          name: VERSION_CODE
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Debug VERSION value
        run: |
          echo "VERSION: ${{ vars.VERSION_CODE }}"

      - name: Set up Docker Container .env
        run: |
          echo "${{ secrets.ENV_CONTENT }}" >> .env.production
          source .env.production

      - name: Build Docker image
        run: |
          docker build -t primetimetran/turboship:${{ vars.VERSION_CODE }} \
            --build-arg HOST=${{ vars.HOST }} \
            --build-arg HOST_URL=${{ vars.HOST_URL }} \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            . --platform linux/amd64

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push primetimetran/turboship:${{ vars.VERSION_CODE }}

      - name: Fetch latest Docker image tag
        id: get_latest_tag
        run: |
          latest_tag=$(curl -s "https://hub.docker.com/v2/repositories/primetimetran/turboship/tags/" | jq -r '.results | .[].name' | grep -v "latest" | sort -V | tail -n 1)
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Update service YAML with latest tag
        run: |
          sed -i "s|docker.io/primetimetran/turboship:latest|docker.io/primetimetran/turboship:${{ vars.VERSION_CODE }}|g" service.yaml

      - name: Deploy to Cloud Run
        run: gcloud run services replace service.yaml --project turboship-dev
